version: "3.8"

services:
  backend:
    build: ./backend
    container_name: kanban-backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/tasks.json:/root/tasks.json

  frontend:
    build: ./frontend
    container_name: kanban-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
