version: "3.8"

services:
  backend:
    build: ./backend
    container_name: kanban-backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/tasks.json:/app/tasks.json
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:8080/",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  frontend:
    build: ./frontend
    container_name: kanban-frontend
    ports:
      - "5173:80"
    depends_on:
      backend:
        condition: service_healthy
